Refactor curl

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,47 +25,40 @@ jobs:
             - run:
                 name: Send pending status
                 command: |
-                  curl \
-                    --request POST \
-                    --url https://api.github.com/repos/metanerd/circleci-test/statuses/<< pipeline.parameters.external_sha >> \
-                    --user ${GITHUB_USER}:${GITHUB_USER_TOKEN} \
-                    --header 'content-type: application/json' \
-                    --data '{"state": "pending", "description": "Why are you using the wrong sha? Running Enterprise master with << pipeline.parameters.external_sha >> . ", "context": "circleci/enterprise-integration"}'
+                  /go/src/github.com/metanerd/.circleci/create-github-status.sh \
+                    "<< pipeline.parameters.external_sha >>" \
+                    "pending" \
+                    "Running enterprise master with << pipeline.parameters.external_sha >>" \
+                    "circleci/enterprise-integration"
+            - run:
+                name: set trap
+                command: |
+                  /go/src/github.com/metanerd/.circleci/fail-trap.sh "<< pipeline.parameters.external_sha >>" "Failed during step setup. "
+                  trap -p
+                  echo "hello" | grep foo
       - run:
-          name: set trap
+          name: Checkout mattermost-server
           command: |
-            trap 'curl \
-              --request POST \
-              --url https://api.github.com/repos/metanerd/circleci-test/statuses/<< pipeline.parameters.external_sha >> \
-              --user ${GITHUB_USER}:${GITHUB_USER_TOKEN} \
-              --header "Content-Type: application/json" \
-              --data "{\"state\": \"failure\", \"description\": \"Trap got triggered. \", \"context\": \"circleci/enterprise-integration\"}" \
-            ' ERR
-            trap -p
-            echo "hello" | grep foo
-#      - run:
-#          name: Checkout mattermost-server
-#          command: |
-#            mkdir -p ~/.ssh/
-#            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
-#            git clone git@github.com:mattermost/mattermost-server.git
-#
-#            cd mattermost-server
-#            /go/src/github.com/metanerd/.circleci/git-checkout-branch.sh "<< pipeline.parameters.external_branch >>"
-#            git branch
-#      - run:
-#          name: Checkout mattermost-webapp
-#          command: |
-#            ls -la
-#            mkdir -p ~/.ssh/
-#            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
-#            git clone git@github.com:mattermost/mattermost-webapp.git
-#
-#            cd mattermost-webapp
-#            /go/src/github.com/metanerd/.circleci/git-checkout-branch.sh "<< pipeline.parameters.external_branch >>"
-#
-#            export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
-#            echo "$WEBAPP_GIT_COMMIT"
+            mkdir -p ~/.ssh/
+            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+            git clone git@github.com:mattermost/mattermost-server.git
+
+            cd mattermost-server
+            /go/src/github.com/metanerd/.circleci/git-checkout-branch.sh "<< pipeline.parameters.external_branch >>"
+            git branch
+      - run:
+          name: Checkout mattermost-webapp
+          command: |
+            ls -la
+            mkdir -p ~/.ssh/
+            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+            git clone git@github.com:mattermost/mattermost-webapp.git
+
+            cd mattermost-webapp
+            /go/src/github.com/metanerd/.circleci/git-checkout-branch.sh "<< pipeline.parameters.external_branch >>"
+
+            export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
+            echo "$WEBAPP_GIT_COMMIT"
 
 #  build:
 #    docker:
@@ -90,7 +83,6 @@ jobs:
 #      - when:
 #          condition: << pipeline.parameters.external_sha >>
 #          steps:
-#            - run: expr length "${GITHUB_USER_TOKEN}"
 #            - run:
 #                name: Sending success status
 #                command: |
